### ISSUE TITLE
Improve new patch versions releasing

### ISSUE THREAD

**Issue by hatskier** [redstone-finance/redstone-docs#19]
We use docusarus with versioning. It has advantages but complicates the process of pushing new small updates (which happen a lot).

Currently to push a small update (even a typo fix) to the docs we need:
1. Create a PR with changes in the docs folder
2. Merge the PR
3. Create a new version with `yarn docusaurus docs:version 0.1.<PREV_VERSION + 1>
4. Publish the new version

The steps 3 and 4 are currently being made manually on a separate PR or on the main branch, but we can create a github action that will publish a new version automatically (e.g. by creating a new PR)

Another approach to consider is just removing the versioning xD

**Comment by koonopek** [comment]
Xd ,:)

Pozdrawiam,
Michał Konopka

wt., 4 kwi 2023, 16:35 użytkownik Alex Suvorov ***@***.***>
napisał:

**Comment by koonopek** [comment]
@cehali already removed versioning
